# Source config
source_name: 'fleetsu'

# DAG config
dag_id: 'elt_bronze_fleetsu_dag'
dag_template: template_bronze_dag
owner: 'airflow'
start_date_year: 2023
start_date_month: 8
start_date_day: 15
retries: 1
tags:
  - 'bronze'
schedule: '@daily'
catchup: False

# Task config -- Databricks
databricks_conn_id: 'databricks_default'
databricks_workflow_name: bronze_fleetsu_ingestion_workflow
databricks_poll_period: 30
databricks_retry_limit: 3
databricks_retry_delay: 1

# Task config -- dbt
dbt_cloud_conn_id: 'dbt_cloud_default'
dbt_project_id: 2780
dbt_environment_name: deployment_env
dbt_job_name: Build Bronze Fleetsu
dbt_trigger_reason: 'Triggered via Airflow'

# Task config -- MS Teams
msteams_conn_id: 'msteams_default'